### ISSUE TITLE
Footnotes appear as numbers in main text

### ISSUE THREAD

**Issue by Lincsand** [caseyg/knutepunkt2017#124] opened 2017-01-09 11:49 UTC
The marking of footnotes are not consistent. 

Some have numbersmarking just after the word, but at regular text size and style. (This2)
And some have the "regular" FN way, with the number at the top right of the word. 

This needs to be changed so it's consistent throughout the book.
We are using Top right of the word.  If you right click on the footnote marker, it gives you different altneratives on how they should look.

**Comment by caseyg** [comment] 2017-01-09 17:31
Thanks! I will be able to fix this automatically on our end.

Will check off here, as I make sure it's fixed:

- [x] Yesterday
- [x] Today
- [x] Tomorrow

**Comment by caseyg** [comment] 2017-01-13 19:07
(duplicate of #153)

**Comment by caseyg** [comment] 2017-01-13 19:13
Example, to see if the change will fix this:

> See: "Beyond playing to lose" pg. 361

**Comment by caseyg** [comment] 2017-01-15 17:24
Think I can fix this just by checking one box to activate a superscript character style, but should be checked before print.

**Comment by caseyg** [comment] 2017-01-15 18:06
Fixed!

**Closed as completed by caseyg** 2017-01-15 18:06 UTC
