### ISSUE TITLE
Overall: titles and start of lists appearing at the bottom of page

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#191] opened 2017-01-15 03:51 UTC
Needs to be gone through as the last thing in the layout pass tomorrow. - if editors need to work on it, we need Casey-tutorial to not add a ton of extra white space.

**Comment by caseyg** [comment] 2017-01-15 18:19
Closing, bc this is a duplicate of #154.

**Closed as completed by caseyg** 2017-01-15 18:19 UTC
